import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import { useUser } from '@auth0/nextjs-auth0/client'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { user, error,isLoading } = useUser()


  if (user) {
   return (
    <>
      <Head>
        <title>TravelPesa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <div>
            <a
              href="./"
              target=""
              rel="noopener noreferrer"
            >
              <Image
                src="/logo.jpg"
                alt="TravelPesa Logo"
                className={styles.vercelLogo}
                width={150}
                height={48}
                priority
              />
            </a>
          </div>
          <div>
            <Link href='/api/auth/logout'>
              <p>{user.name}</p>
            </Link>
          </div>
        </div>

        <div className={styles.center}>
          <div className={styles.card}>
            <p>Balance: <h3>60,000</h3></p>
          </div>
          <div className={styles.card}>
            <p>Loan limit: <h3>60,000</h3></p>
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="#"
            className={styles.card}
            target=""
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Wallet <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Deposit
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target=""
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              UGX <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Pay with Loan
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target=""
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              CASH <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Pay with Savings
            </p>
          </a>
        </div>

        <div className={styles.grid}>
          <a
            href="#"
            className={styles.card}
            target=""
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              MONEY <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Repay Loan
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target=""
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              PEOPLE <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Share Travel Savings
            </p>
          </a>

          <a
            href="#"
            className={styles.card}
            target=""
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              TRIP <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Honeymoon Savings
            </p>
          </a>
        </div>
        <p>copyright @ 2023</p>
      </main>
    </>
   )
  }
  return (
      <main className={styles.main}>
          <div className={styles.description}>
          <div>
            <a
              href="./"
              target=""
              rel="noopener noreferrer"
            >
              <Image
                src="/logo.jpg"
                alt="TravelPesa Logo"
                className={styles.vercelLogo}
                width={150}
                height={48}
                priority
              />
            </a>
          </div>
          <div>
            
          </div>
        </div>

        <div>
          <Link href="/api/auth/login" className={styles.card}>Login</Link>
        </div>

        <p>copyright @ 2023</p>

      </main>
    )

}
